### PR TITLE
Image based off Alpine Linux

### PR DESCRIPTION
**Pull request by jgomezdans**
Started a PR for this, code happening in the `alpine` branch. 
Addresses #21

### CODE REVIEW

**Comment by jgomezdans** [comment]
Automated build breaks due to stages cacheing changing... Will try to see whether I can clear the cache

**Comment by jgomezdans** [comment]
Seems to work 99% (e.g. loads gdal and stuff), but I have only performed minimal testing. Things that are yet to be tested:

* copying the notebooks folder seems to fail for some obscure reason
* the stuff about mounting the OneDrive is missing in the Dockerfile, probably needs to go somewhere

The image now is short of 3 Gb (<1 Gb compressed), but unless we remove more conda packages, "it is what it is".

Latex packages are still missing.

Finally, I'm not sure alpine is the best for this. Debian-slim is also quite small, and allows us to add gazillions of well-tested packages, and the ubuntu base images are also very small. Ultimately, it's all about the packages you install...

**Comment by jgomezdans** [comment]
@profLewis Just review this if you can, I'll sort out fixing the conflicts so that we don't break the history.

**Comment by profLewis** [comment]
https://hub.docker.com/r/continuumio/miniconda3/tags <https://hub.docker.com/r/continuumio/miniconda3/tags>

Is tiny …

I think use this as the base (not alpine)

**Review by profLewis — APPROVED** [review]

**Comment by profLewis** [comment]
I agree that we could go to some lengths to make the docker smaller …
But the amount of effort and code involved is not sustainable … Jose has built an alpine version, & re-used a lot of scripts from Jupyter notebooks. But if Jupyter change their scripts, we are out of date. Its not worth it.

If space really matters so much for download (& were really just talking less that 2.5 GB here remember …) then do the things Jose picked up on such as delete latex. Until you need it.

I also had a quick go at basing on miniconda, rather than the Jupyter. It can be done, but you end top having to do all of the things they did in Jupyter anyway. Or you can use some non-official one, that will be abandoned a year down the road.

So, I say, forget this idea of alpine. Keep that for small IoT things or whatever its designed for. Sorry you’ve put so much effort in Jose. IObs you can still keep your version, but its not what I think we should propose and share.

We actively decided we want notebooks, and that Docker was worthwhile. So use docker Jupyter. The minimal one is fine as we add our own bespoke stuff on top.

On related things, Ive got a script https://github.com/jgomezdans/geog_docker/blob/master/init_dist <https://github.com/jgomezdans/geog_docker/blob/master/init_dist> that tries to mimic the setup expressed in docker file. I think that works on most linux/unix and is useful for testing with the same set, outside of docker.

Feng: is the base setup feasible with its ~2.5GB now? Id assume that Jupyter stuff was mirrored, and that’s 1+ GB of it all …



Lewis

**Comment by profLewis** [comment]
https://www.docker.com/docker-news-and-press/docker-brings-docker-public-registry-china-expand-developer-adoption-and-fuel <https://www.docker.com/docker-news-and-press/docker-brings-docker-public-registry-china-expand-developer-adoption-and-fuel>

**Comment by profLewis** [comment]
Hi,

I have tried with miniconda as well and it works as a root user, and jupyter minimal has some extra considerations of running the jupyter under a user, which causes a lot of extra bash commands, which is necessary in same case I suppose. But if you use it inside a docker, it should be generally fine to run it under root.

The instruction provided by miniconda docker to run a jupyter:

docker run -i -t -p 8888:8888 continuumio/miniconda3 /bin/bash -c "/opt/conda/bin/conda install jupyter -y --quiet && mkdir /opt/notebooks && /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser"

And I think the above will work and adding extra packages should also be fine.

But if we were going to stick with the official docker image, we will have the continuous support and update without worrying the installation of jupyter (though it's just a conda package). I agree with that for the consideration of later maintenance of this course, it would be good to keep things robust.

As I said before, 2,5 GBs image is not impossible and it's just you need to wait several hours if the internet is not optimal, and I think the students just need to wait till it finish.

There are some suggestions for students using docker on Linux, they may fill the /var/lib/docker directory. If they have limited disk partition for /var folder, they may cause problems of starting their machine...Do not ask how I find it out...

Best,

Feng.


________________________________

**Comment by profLewis** [comment]
Thanks — I don’t like that idea of running as root, even in a docker. It’s bad practice. I guess it’s because it’s more lines of code to set up a user?

Do you think we can give a minimum spec machine for ram & free space etc? 

Wrt your space comments, why they would have a separate /var partition. Maybe that goes in a Faq? ( it doesn’t run ... what do I do ...

- Check disk space (esp on required partition)
- check you have docker installed ...
- check the intermediate docker images run ...

In a different order.

Lewis

Professor Philip Lewis, UCL

**Comment by profLewis** [comment]
I just had to install ms visual studio on my boot camp ... 25GB for the basics!!

(I’ll tell you why later, if it works)

Lewis

Professor Philip Lewis, UCL

**Comment by profLewis** [comment]
Hi,

Though the idea of build docker from Miniconda is not going to be the solution, I have made it available through my docker account and set the Jupyter to run under a user named jeremy. I have put the geog0111 notebooks into it as well, and the final compressed docker image is 1.15 GB. You can test it with:

docker pull marcyin/geog0111:latest

It's a lot of 'fun' to develop the docker file and automatically deploy the docker image. But I am little confused by the Jupyter nbextensions, I mean I have set the docker extensions same as  Jose has done, but do not know whether it was set properly....

I think number of cpu cores is not a big problem, and ram should be around 2GB (maybe even smaller...). The uncompressed geog docker image is 5.92 GB and you need to store the satellite images. But you can avoid it by only store the clipped part, which should be much smaller. I would say around 20 GB? But I think the course is not so computationally and data intensive, so it's still probably overkill.

The partition was done by Tom long time ago and he set 20 GB limit to that folder, which could be easily filled up if you pulled several docker images and try to build docker as well....

I think you can use VS code on Mac, and you can link the docker container to the VS code and edit and run code in VS code but the execution is done in the container. This is a good idea I guess, since it acting as some kind of sandbox and also isolate all the processes from your local computing platform.

Best,

Feng.
________________________________

**Comment by profLewis** [comment]
Thanks Feng — I’ll take a look. I’m playing with my lidar for a bit today (Beau is on a play date :-)

If this works the same, then maybe we should use this then ... what’s the github link?

We’d need to do a generic version without the geog0111 and put the user to jovyan or ucl or similar. I’m guessing the user setup will break my mimic script. 

Jose maybe put the generic version on a branch?

Lewis

Professor Philip Lewis, UCL

**Comment by profLewis** [comment]
The lidar images are very cool and I guess you would be cool to test your ray tracer with it as well.

The GitHub repo is here:

https://github.com/MarcYin/BuildGeog0111

A generic one is just delete two lines in the Docker file, which dose the clone of geog0111. The user is named after  Jeremy Bentham, and I though it would be good, but change to UCL would be good as well.

Feng.
________________________________

**Pull request merged**
